  # See http://www.appveyor.com/docs/appveyor-yml for many more options

build: false
version: 0.1.{build}

#images

image:
  - Visual Studio 2019
  - Ubuntu

# Set build info
environment:
  environment: development
  version: 0.1.$(appveyor_build_number)
  PGUSER: postgres
  PGPASSWORD: Password12!
  AssentNonInteractive: true

for:
  - matrix:
      only:
        - image: Visual Studio 2019
    environment:
        mssql_instance: localhost\SQL2017
        scenario: windows
    services:
      - mssql2017
      - mysql
      - postgresql
    before_build:
      - ps: dotnet new tool-manifest
      - ps: dotnet tool install Cake.Tool --version 1.1.0
      - ps: Invoke-WebRequest https://cakebuild.net/download/bootstrapper/dotnet-tool/windows -OutFile build.ps1
    build_script:
      - ps: .\build.ps1
    after_build:
      - ps: .\build\copy_build_files.ps1

    before_test:
      - SET PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
      - psql -c "CREATE USER sa WITH SUPERUSER PASSWORD 'Password12!';" -U postgres
      - ps: .\tests\appveyor.prep.ps1


  - matrix:
      only:
        - image: Ubuntu
    environment:
        mssql_instance: localhost
        scenario: all
        TZ: GMT
    services:
      - mssql
      - mysql
      - postgresql
    before_test:
      - sudo -u postgres psql -c "CREATE USER sa WITH SUPERUSER PASSWORD 'Password12!';"
      - ps: .\tests\appveyor.prep.ps1
      - docker run --name dbops-oracle -d -p 1521:1521 -e ORACLE_ALLOW_REMOTE=true wnameless/oracle-xe-11g-r2

after_test:
  - ps: .\tests\appveyor.post.ps1
test_script:
  - ps: .\tests\appveyor.pester.ps1
  # Collecting results
  - ps: .\tests\appveyor.pester.ps1 -Finalize


# Set alternative clone folder
#clone_folder: c:\github\dbops



#on_finish:
#  - ps:
