trigger:
  branches:
    include:
    - main
  paths:
    exclude:
      - docs
      - README.md
# resources:
#   repositories:
#   - repository: self
#     type: git
#     ref: main
jobs:
- job: cut_new_release_branch
  displayName: Agent phase
  cancelTimeoutInMinutes: 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
    persistCredentials: True
  - task: PowerShell@2
    displayName: Bump up version
    inputs:
      filePath: .\build\bump_version.ps1
      arguments: .\dbops.psd1
  - task: PowerShell@2
    displayName: Cut a release branch
    inputs:
      filePath: .\build\git_release.ps1
    env:
      git_user_email: $(gitUserEmail)
      git_username: $(gitUsername)