# 'Allow scripts to access the OAuth token' was selected in pipeline.  Add the following YAML to any steps requiring access:
#       env:
#           MY_ACCESS_TOKEN: $(System.AccessToken)
# Variable 'gitcommitmessage' was defined in the Variables tab
# Variable 'system.prefergit' was defined in the Variables tab
trigger:
  branches:
    include:
    - release/*
jobs:
- job: build_artifacts
  displayName: Agent phase
  cancelTimeoutInMinutes: 1
  pool:
    vmImage: windows-2019
  steps:
  - checkout: self
    clean: true
    persistCredentials: True
  - task: PowerShell@2
    displayName: Prepare build
    inputs:
      filePath: .\build\build_prep.ps1
  - task: PowerShell@2
    displayName: Build libraries
    inputs:
      filePath: .\build.ps1
  - task: PowerShell@2
    displayName: Copy libraries
    inputs:
      filePath: .\copy_build_files.ps1
      arguments: .\dbops
  - task: PowerShell@2
    displayName: Create folder and move files to it
    inputs:
      scriptType: inlineScript
      inlineScript: |
        New-Item dbops -Type Directory
        Get-Item bin, functions, internal, *.ps*1, license.txt | Foreach-Object { Move-Item $_ .\dbops }
        Write-Host "##vso[build.addbuildtag]Release"
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: dbops'
    env:
      MY_ACCESS_TOKEN: $(System.AccessToken)
    inputs:
      PathtoPublish: .\dbops
      ArtifactName: dbops