name: CI
on: [pull_request]

jobs:
  build:
    name: Module imports on all platforms
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Perform the import
      shell: pwsh
      run: Install-Module PSFramework -Force; Import-Module ./dbops.psd1 -ErrorAction Stop
